softname: fiddler
softshowname: Fiddler
softofficialhomelink: https://www.telerik.com/fiddler
softofficialdownloadlink: https://www.telerik.com/download/fiddler
# è½¯ä»¶å›¾æ ‡ æœ€å°æ˜¯ 18px*18px æˆ–è€…æ˜¯48px*48px
softlogo: statics/soft/fiddler/logo.png
# è½¯ä»¶åˆ—è¡¨é¡µbannerå›¾ æœ€å°æ˜¯ 380px*178px æˆ–è€…æ˜¯ 1172px*568px
softbanner: statics/soft/fiddler/banner.png
# è½¯ä»¶ä¸€å¥è¯æè¿°
softshortcomment: æŠ“åŒ…å·¥å…·
# è½¯ä»¶ä»‹ç»
softcomment: ç½‘é¡µè°ƒè¯•å·¥å…·ï¼Œä¼˜ç§€æŠ“åŒ…å·¥å…·
softspecialtip: æŠ“åŒ…æŠ“å¾—å¥½ï¼Œç‰¢é¥­åƒåˆ°é¥±ğŸ˜‚
# è½¯ä»¶åˆ†ç±»,å¯ä»¥å¤šä¸ª
softcategory:
    - tool
softicon:
    - free
# æ˜¯å¦éœ€è¦åŒæ­¥
softsync: true
# [å¯é€‰]æ˜¯å¦æ˜¾ç¤ºåœ¨è½¯ä»¶åˆ—è¡¨é¡µ,é»˜è®¤ä¸ºtrue , å¯é€‰å€¼: true false
softshowinlist: true
# [å¯é€‰]æ˜¯å¦æ˜¾ç¤ºè½¯ä»¶å¹³å°,é€‚åˆå¹³å°åªæœ‰å°‘é‡å‡ ä¸ªçš„æ—¶å€™,å¾ˆå¤šå¹³å°(5ä¸ªä»¥ä¸Š)ä¸è¦å¼€,é»˜è®¤false
softshowplatform: true
release:
    win:
        platform: win
        platformshowname: Windows
        link: https://telerik-fiddler.s3.amazonaws.com/fiddler/fiddler-version-files/new4.txt
        linktype: txt
        rule:
            parser: \App\Parser\FiddlerParser
            datatype: string
            download:
                filename:
                    type: string
                    value: FiddlerSetup-{{version}}.exe
                fileurl:
                    type: string
                    value: https://telerik-fiddler.s3.amazonaws.com/fiddler/FiddlerSetup.exe
                filesize:
                    type: fromfile
                fileuploadprefix:
                    type: string
                    value: app/{{softname}}/{{platform}}/{{version}}/