softname: phpstorm
softshowname: PhpStorm
softofficialhomelink: https://www.jetbrains.com/phpstorm/
softofficialdownloadlink: https://www.jetbrains.com/phpstorm/download
# 软件图标
softlogo: statics/soft/phpstorm/logo.svg
# 软件列表页banner图
softbanner: statics/soft/phpstorm/banner.png
# 软件一句话描述
softshortcomment: 最佳PHP开发工具
# 软件介绍
softcomment: PHP集成开发工具
# 软件分类,可以多个
softcategory:
    - ide
softicon:
    - paid
softspecialtip: 特别说明
# 是否需要同步
softsync: true
# [可选]是否显示在软件列表页,默认为true , 可选值: true false
softshowinlist: true
# [可选]是否显示软件平台,适合平台只有少量几个的时候,很多平台(5个以上)不要开,默认false
softshowplatform: true
release:
    win:
        platform: win
        platformshowname: Windows
        link: https://data.services.jetbrains.com/products?code=PS&release.type=release
        linktype: json
        linkrequestmethod: GET
        # 获取远程版本最大数量,可以控制丢弃一些老的版本,默认50
        getversionmaxnum: 5
        # 展示到页面时版本最大数量,多余的版本会显示在归档中,默认5
        showversionmaxnum: 2
        # 是否按版本类型进行分类显示,默认为false
        showgroupbychannel: true
        rule:
            datatype: array
            root: 0.releases
            version: version
            time: date
            channel: type
            notes: notesLink
            features: whatsnew
            download:
                root: downloads.windows
                filename:
                    type: path
                    value: link
                filehash:
                    type: url
                    value: checksumLink
                    # hash链接内容分隔符
                    delimiter: " "
                filesize: size
                fileurl:
                    type: field
                    value: link
    win-zip:
        platform: win-zip
        platformshowname: Windows-ZIP
        link: https://data.services.jetbrains.com/products?code=PS&release.type=release
        linktype: json
        linkrequestmethod: GET
        # 获取远程版本最大数量,可以控制丢弃一些老的版本,默认50
        getversionmaxnum: 5
        # 展示到页面时版本最大数量,多余的版本会显示在归档中,默认5
        showversionmaxnum: 5
        # 是否按版本类型进行分类显示,默认为false
        showgroupbychannel: true
        rule:
            datatype: array
            root: 0.releases
            version: version
            time: date
            channel: type
            notes: notesLink
            features: whatsnew
            download:
                root: downloads.windowsZip
                filename:
                    type: path
                    value: link
                filehash:
                    type: url
                    value: checksumLink
                    # hash链接内容分隔符
                    delimiter: " "
                filesize: size
                fileurl:
                    type: field
                    value: link
    mac:
        platform: mac
        platformshowname: MacOS
        link: https://data.services.jetbrains.com/products?code=PS&release.type=release
        linktype: json
        linkrequestmethod: GET
        # 获取远程版本最大数量,可以控制丢弃一些老的版本,默认50
        getversionmaxnum: 5
        # 展示到页面时版本最大数量,多余的版本会显示在归档中,默认5
        showversionmaxnum: 5
        # 是否按版本类型进行分类显示,默认为false
        showgroupbychannel: true
        rule:
            datatype: array
            root: 0.releases
            version: version
            time: date
            channel: type
            notes: notesLink
            features: whatsnew
            download:
                root: downloads.mac
                filename:
                    type: path
                    value: link
                filehash:
                    type: url
                    value: checksumLink
                    # hash链接内容分隔符
                    delimiter: " "
                filesize: size
                fileurl:
                    type: field
                    value: link
    linux:
        platform: linux
        platformshowname: Linux
        link: https://data.services.jetbrains.com/products?code=PS&release.type=release
        linktype: json
        linkrequestmethod: GET
        # 获取远程版本最大数量,可以控制丢弃一些老的版本,默认50
        getversionmaxnum: 5
        # 展示到页面时版本最大数量,多余的版本会显示在归档中,默认5
        showversionmaxnum: 5
        # 是否按版本类型进行分类显示,默认为false
        showgroupbychannel: true
        rule:
            datatype: array
            root: 0.releases
            version: version
            time: date
            channel: type
            notes: notesLink
            features: whatsnew
            download:
                root: downloads.linux
                filename:
                    type: path
                    value: link
                filehash:
                    type: url
                    value: checksumLink
                    # hash链接内容分隔符
                    delimiter: " "
                filesize: size
                fileurl:
                    type: field
                    value: link