softname: phpstorm
softshowname: PhpStorm
softofficialhomelink: https://www.jetbrains.com/phpstorm/
softofficialdownloadlink: https://www.jetbrains.com/phpstorm/download
# è½¯ä»¶å›¾æ ‡
softlogo: statics/soft/phpstorm/logo.svg
# è½¯ä»¶åˆ—è¡¨é¡µbannerå›¾
softbanner: statics/soft/phpstorm/banner.png
# è½¯ä»¶ä¸€å¥è¯æè¿°
softshortcomment: æœ€ä½³PHPå¼€å‘å·¥å…·
# è½¯ä»¶ä»‹ç»
softcomment: PHPé›†æˆå¼€å‘å·¥å…·
# è½¯ä»¶åˆ†ç±»,å¯ä»¥å¤šä¸ª
softcategory:
    - ide
softicon:
    - paid
softspecialtip: PHPæ˜¯ä¸–ç•Œä¸Šæœ€å¥½çš„è¯­è¨€ğŸ˜
# æ˜¯å¦éœ€è¦åŒæ­¥
softsync: true
# [å¯é€‰]æ˜¯å¦æ˜¾ç¤ºåœ¨è½¯ä»¶åˆ—è¡¨é¡µ,é»˜è®¤ä¸ºtrue , å¯é€‰å€¼: true false
softshowinlist: true
# [å¯é€‰]æ˜¯å¦æ˜¾ç¤ºè½¯ä»¶å¹³å°,é€‚åˆå¹³å°åªæœ‰å°‘é‡å‡ ä¸ªçš„æ—¶å€™,å¾ˆå¤šå¹³å°(5ä¸ªä»¥ä¸Š)ä¸è¦å¼€,é»˜è®¤false
softshowplatform: true
release:
    win:
        platform: win
        platformshowname: Windows
        link: https://data.services.jetbrains.com/products?code=PS&release.type=release
        linktype: json
        linkrequestmethod: GET
        # è·å–è¿œç¨‹ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¯ä»¥æ§åˆ¶ä¸¢å¼ƒä¸€äº›è€çš„ç‰ˆæœ¬,é»˜è®¤50
        getversionmaxnum: 5
        # å±•ç¤ºåˆ°é¡µé¢æ—¶ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¤šä½™çš„ç‰ˆæœ¬ä¼šæ˜¾ç¤ºåœ¨å½’æ¡£ä¸­,é»˜è®¤5
        showversionmaxnum: 2
        # æ˜¯å¦æŒ‰ç‰ˆæœ¬ç±»å‹è¿›è¡Œåˆ†ç±»æ˜¾ç¤º,é»˜è®¤ä¸ºfalse
        showgroupbychannel: true
        rule:
            datatype: array
            root: 0.releases
            version: version
            time: date
            channel: type
            notes: notesLink
            features: whatsnew
            download:
                root: downloads.windows
                filename:
                    type: path
                    value: link
                filehash:
                    type: url
                    value: checksumLink
                    # hashé“¾æ¥å†…å®¹åˆ†éš”ç¬¦
                    delimiter: " "
                filesize: size
                fileurl:
                    type: field
                    value: link
    win-zip:
        platform: win-zip
        platformshowname: Windows-ZIP
        link: https://data.services.jetbrains.com/products?code=PS&release.type=release
        linktype: json
        linkrequestmethod: GET
        # è·å–è¿œç¨‹ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¯ä»¥æ§åˆ¶ä¸¢å¼ƒä¸€äº›è€çš„ç‰ˆæœ¬,é»˜è®¤50
        getversionmaxnum: 5
        # å±•ç¤ºåˆ°é¡µé¢æ—¶ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¤šä½™çš„ç‰ˆæœ¬ä¼šæ˜¾ç¤ºåœ¨å½’æ¡£ä¸­,é»˜è®¤5
        showversionmaxnum: 5
        # æ˜¯å¦æŒ‰ç‰ˆæœ¬ç±»å‹è¿›è¡Œåˆ†ç±»æ˜¾ç¤º,é»˜è®¤ä¸ºfalse
        showgroupbychannel: true
        rule:
            datatype: array
            root: 0.releases
            version: version
            time: date
            channel: type
            notes: notesLink
            features: whatsnew
            download:
                root: downloads.windowsZip
                filename:
                    type: path
                    value: link
                filehash:
                    type: url
                    value: checksumLink
                    # hashé“¾æ¥å†…å®¹åˆ†éš”ç¬¦
                    delimiter: " "
                filesize: size
                fileurl:
                    type: field
                    value: link
    mac:
        platform: mac
        platformshowname: MacOS
        link: https://data.services.jetbrains.com/products?code=PS&release.type=release
        linktype: json
        linkrequestmethod: GET
        # è·å–è¿œç¨‹ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¯ä»¥æ§åˆ¶ä¸¢å¼ƒä¸€äº›è€çš„ç‰ˆæœ¬,é»˜è®¤50
        getversionmaxnum: 5
        # å±•ç¤ºåˆ°é¡µé¢æ—¶ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¤šä½™çš„ç‰ˆæœ¬ä¼šæ˜¾ç¤ºåœ¨å½’æ¡£ä¸­,é»˜è®¤5
        showversionmaxnum: 5
        # æ˜¯å¦æŒ‰ç‰ˆæœ¬ç±»å‹è¿›è¡Œåˆ†ç±»æ˜¾ç¤º,é»˜è®¤ä¸ºfalse
        showgroupbychannel: true
        rule:
            datatype: array
            root: 0.releases
            version: version
            time: date
            channel: type
            notes: notesLink
            features: whatsnew
            download:
                root: downloads.mac
                filename:
                    type: path
                    value: link
                filehash:
                    type: url
                    value: checksumLink
                    # hashé“¾æ¥å†…å®¹åˆ†éš”ç¬¦
                    delimiter: " "
                filesize: size
                fileurl:
                    type: field
                    value: link
    linux:
        platform: linux
        platformshowname: Linux
        link: https://data.services.jetbrains.com/products?code=PS&release.type=release
        linktype: json
        linkrequestmethod: GET
        # è·å–è¿œç¨‹ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¯ä»¥æ§åˆ¶ä¸¢å¼ƒä¸€äº›è€çš„ç‰ˆæœ¬,é»˜è®¤50
        getversionmaxnum: 5
        # å±•ç¤ºåˆ°é¡µé¢æ—¶ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¤šä½™çš„ç‰ˆæœ¬ä¼šæ˜¾ç¤ºåœ¨å½’æ¡£ä¸­,é»˜è®¤5
        showversionmaxnum: 5
        # æ˜¯å¦æŒ‰ç‰ˆæœ¬ç±»å‹è¿›è¡Œåˆ†ç±»æ˜¾ç¤º,é»˜è®¤ä¸ºfalse
        showgroupbychannel: true
        rule:
            datatype: array
            root: 0.releases
            version: version
            time: date
            channel: type
            notes: notesLink
            features: whatsnew
            download:
                root: downloads.linux
                filename:
                    type: path
                    value: link
                filehash:
                    type: url
                    value: checksumLink
                    # hashé“¾æ¥å†…å®¹åˆ†éš”ç¬¦
                    delimiter: " "
                filesize: size
                fileurl:
                    type: field
                    value: link