softname: postman
softshowname: Postman
softofficialhomelink: https://www.getpostman.com
softofficialdownloadlink: https://www.postman.com/downloads/
# è½¯ä»¶å›¾æ ‡
softlogo: statics/soft/postman/logo.png
# è½¯ä»¶åˆ—è¡¨é¡µbannerå›¾
softbanner: statics/soft/postman/banner.png
# è½¯ä»¶ä¸€å¥è¯æè¿°
softshortcomment: APIè°ƒè¯•
# è½¯ä»¶ä»‹ç»
softcomment: APIæ¥å£å¼€å‘è°ƒè¯•å·¥å…·
softspecialtip: æˆ‘æ‰ä¸å‘Šè¯‰ä½ è¿™ä¸ªä¸œè¥¿ä¹Ÿèƒ½æŠ“åŒ…ğŸ˜
# è½¯ä»¶åˆ†ç±»,å¯ä»¥å¤šä¸ª
softcategory:
    - tool
softicon:
    - paid
# æ˜¯å¦éœ€è¦åŒæ­¥
softsync: true
# [å¯é€‰]æ˜¯å¦æ˜¾ç¤ºåœ¨è½¯ä»¶åˆ—è¡¨é¡µ,é»˜è®¤ä¸ºtrue , å¯é€‰å€¼: true false
softshowinlist: true
# [å¯é€‰]æ˜¯å¦æ˜¾ç¤ºè½¯ä»¶å¹³å°,é€‚åˆå¹³å°åªæœ‰å°‘é‡å‡ ä¸ªçš„æ—¶å€™,å¾ˆå¤šå¹³å°(5ä¸ªä»¥ä¸Š)ä¸è¦å¼€,é»˜è®¤false
softshowplatform: true
release:
    win:
        platform: win
        platformshowname: Windows
        link: https://dl.pstmn.io/changelog?channel=stable&platform=win
        linktype: json
        linkrequestmethod: GET
        # è·å–è¿œç¨‹ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¯ä»¥æ§åˆ¶ä¸¢å¼ƒä¸€äº›è€çš„ç‰ˆæœ¬,é»˜è®¤50
        getversionmaxnum: 6
        # å±•ç¤ºåˆ°é¡µé¢æ—¶ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¤šä½™çš„ç‰ˆæœ¬ä¼šæ˜¾ç¤ºåœ¨å½’æ¡£ä¸­,é»˜è®¤5
        showversionmaxnum: 5
        # æ˜¯å¦æŒ‰ç‰ˆæœ¬ç±»å‹è¿›è¡Œåˆ†ç±»æ˜¾ç¤º,é»˜è®¤ä¸ºfalse
        showgroupbychannel: true
        rule:
            datatype: array
            root: changelog
            version: name
            time: createdAt
            channel: channel
            notes: notes
            features: notes.Features
            gennotespagepath: app/{{softname}}/{{platform}}/{{version}}/releasenotes.html
            download:
                root: assets
                filename:
                    type: field
                    value: name
                filehash:
                    type: field
                    value: hash
                filesize: size
                fileurl:
                    type: field
                    value: url
                fileuploadprefix:
                    type: string
                    value: app/{{softname}}/win/{{version}}/
    mac:
        platform: mac
        platformshowname: MacOS
        link: https://dl.pstmn.io/changelog?channel=stable&platform=osx
        linktype: json
        linkrequestmethod: GET
        # è·å–è¿œç¨‹ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¯ä»¥æ§åˆ¶ä¸¢å¼ƒä¸€äº›è€çš„ç‰ˆæœ¬,é»˜è®¤50
        getversionmaxnum: 6
        # å±•ç¤ºåˆ°é¡µé¢æ—¶ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¤šä½™çš„ç‰ˆæœ¬ä¼šæ˜¾ç¤ºåœ¨å½’æ¡£ä¸­,é»˜è®¤5
        showversionmaxnum: 5
        # æ˜¯å¦æŒ‰ç‰ˆæœ¬ç±»å‹è¿›è¡Œåˆ†ç±»æ˜¾ç¤º,é»˜è®¤ä¸ºfalse
        showgroupbychannel: true
        rule:
            datatype: array
            root: changelog
            version: name
            time: createdAt
            notes: notes
            features: notes.Features
            download:
                root: assets
                filename:
                    type: field
                    value: name
                filehash:
                    type: field
                    value: hash
                filesize: size
                fileurl:
                    type: field
                    value: url
                fileuploadprefix:
                    type: string
                    value: app/{{softname}}/mac/{{version}}/
    linux:
        platform: linux
        platformshowname: Linux(x64)
        link: https://dl.pstmn.io/changelog?channel=stable&platform=linux
        linktype: json
        linkrequestmethod: GET
        # è·å–è¿œç¨‹ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¯ä»¥æ§åˆ¶ä¸¢å¼ƒä¸€äº›è€çš„ç‰ˆæœ¬,é»˜è®¤50
        getversionmaxnum: 6
        # å±•ç¤ºåˆ°é¡µé¢æ—¶ç‰ˆæœ¬æœ€å¤§æ•°é‡,å¤šä½™çš„ç‰ˆæœ¬ä¼šæ˜¾ç¤ºåœ¨å½’æ¡£ä¸­,é»˜è®¤5
        showversionmaxnum: 5
        # æ˜¯å¦æŒ‰ç‰ˆæœ¬ç±»å‹è¿›è¡Œåˆ†ç±»æ˜¾ç¤º,é»˜è®¤ä¸ºfalse
        showgroupbychannel: true
        rule:
            datatype: array
            root: changelog
            version: name
            time: createdAt
            notes: notes
            features: notes.Features
            download:
                root: assets
                filename:
                    type: field
                    value: name
                filehash:
                    type: field
                    value: hash
                filesize: size
                fileurl:
                    type: field
                    value: url
                fileuploadprefix:
                    type: string
                    value: app/{{softname}}/linux/{{version}}/
