name: Sync Task

on: [push]

jobs:
  _Test_:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: è·å–IPåœ°å€
      run: curl ipinfo.io
    - name: PHPç‰ˆæœ¬
      run: php -v
    - name: åŒæ­¥
      run: |
        php sync/index.php
      env:
        QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
        QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
    - name: å®‰è£… SSH key of Gitee
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        #config: ${{ secrets.CONFIG }} # ssh_config; optional
    - name: æäº¤æ–‡ä»¶åˆ° Gitee
      run: |
        ./deploy/deploy2gitee.sh
    - name: æäº¤æ–‡ä»¶åˆ° Github
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "ğŸ¤–bot: Auto Update" -a
    - name: æ¨é€æ›´æ–°
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}